export const {
    REACT_APP_DOMAIN: DOMAIN = process.env.REACT_APP_DOMAIN,
    REACT_APP_BACKEND_URL: BACKEND_URL = process.env.BACKEND_URL,
    REACT_APP_FRONTEND_URL: FRONTEND_URL = process.env.FRONTEND_URL,
    REACT_APP_SESSION_COOKIE_NAME: SESSION_COOKIE_NAME = process.env
        .REACT_APP_SESSION_COOKIE_NAME,
} = process.env;
