version: '3.5'

services:
  db:
    image: mysql
    env_file:
      - .env
    environment:
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DB
    volumes:
      - ./.docker/mysql-data:/var/lib/msql/data
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"

  backend:
    depends_on:
      - db
    build: ./server
    volumes:
      - ./server:/usr/src/app
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - PORT=${BACKEND_PORT}
      - BACKEND_URL=http://localhost:${BACKEND_PORT}
      - FRONTEND_URL=http://localhost:${FRONTEND_PORT}
      - FRONTEND_DOMAIN=${DOMAIN}
    ports: 
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    build: ./client
    command: npm start
    env_file:
      - .env
    volumes:
      - ./client:/app
    environment:
      - PORT=${FRONTEND_PORT}
      - REACT_APP_BACKEND_URL=http://localhost:${BACKEND_PORT}
      - REACT_APP_SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME}
      - REACT_APP_DOMAIN=${DOMAIN}
      - REACT_APP_FRONTEND_URL=http://localhost:${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    stdin_open: true
